# Generated by Django 5.2.6 on 2025-09-21 13:44

import django.core.validators
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('skills', models.CharField(help_text='Comma separated list of skills', max_length=512)),
                ('github_link', models.URLField(blank=True)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(120)])),
                ('resume', models.FileField(upload_to=jobs.models.resume_upload_to)),
                ('college_name', models.CharField(max_length=255)),
                ('passing_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
